# Generated by Django 3.0.6 on 2020-06-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AbilityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abilities', models.ManyToManyField(related_name='ability', to='ktGuide.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialists', models.ManyToManyField(related_name='specialist', to='ktGuide.Specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weapon_range', models.IntegerField()),
                ('weapon_type', models.CharField(max_length=50)),
                ('s', models.IntegerField()),
                ('ap', models.IntegerField()),
                ('d', models.IntegerField()),
                ('abilities', models.CharField(max_length=1000)),
                ('pts', models.IntegerField()),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktGuide.Army')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weapons', models.ManyToManyField(related_name='weapon', to='ktGuide.Weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('m', models.IntegerField()),
                ('ws', models.IntegerField()),
                ('bs', models.IntegerField()),
                ('s', models.IntegerField()),
                ('t', models.IntegerField()),
                ('w', models.IntegerField()),
                ('a', models.IntegerField()),
                ('ld', models.IntegerField()),
                ('sv', models.IntegerField()),
                ('max_units', models.CharField(max_length=50)),
                ('point_value', models.IntegerField()),
                ('ability_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktGuide.AbilityList')),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktGuide.Army')),
                ('specialist_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktGuide.SpecialistList')),
                ('weapons_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ktGuide.WeaponList')),
            ],
        ),
    ]
