# Generated by Django 3.0.6 on 2020-07-01 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ktGuide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Bio goes here', max_length=800),
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('guide_desc', models.CharField(max_length=10000)),
                ('point_value', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktGuide.Army')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('units', models.ManyToManyField(related_name='units', to='ktGuide.Unit')),
                ('weapons', models.ManyToManyField(related_name='weapons', to='ktGuide.Weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ktGuide.Guide')),
            ],
        ),
    ]
