# Generated by Django 3.0.6 on 2020-06-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktGuide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_range',
            field=models.CharField(max_length=50),
        ),
    ]
