# Generated by Django 3.0.6 on 2020-06-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktGuide', '0002_auto_20200630_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='s',
            field=models.CharField(max_length=50),
        ),
    ]
